# Generated by Django 5.1.3 on 2024-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
