# Generated by Django 5.1.3 on 2024-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="image",
            field=models.ImageField(upload_to="media/avatars/"),
        ),
    ]
