# Generated by Django 5.1.3 on 2024-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("couple", "Couple"),
                    ("Neural", "Neural"),
                ],
                default="Neural",
                max_length=7,
            ),
        ),
    ]
