# Generated by Django 5.1.3 on 2024-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
