# Generated by Django 5.1.3 on 2024-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_account",
            "0003_customuser_national_id_number_customuser_nationality_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nationality",
            field=models.CharField(
                choices=[("iranian", "Iranian"), ("foreigner", "Foreigner")],
                max_length=9,
            ),
        ),
    ]
