# Generated by Django 5.1.3 on 2024-12-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_club", "0009_remove_membershipclub_user"),
        ("user_account", "0004_alter_customuser_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="membership",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="membership_club.membershipclub",
            ),
        ),
    ]
