# Generated by Django 5.1.3 on 2024-12-04 15:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="total_price",
            field=models.DecimalField(
                decimal_places=5,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="shopping_cart.shoppingcart",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
