# Generated by Django 5.1.3 on 2024-12-04 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping_cart",
            "0002_shoppingcart_status_alter_shoppingcart_total_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
