# Generated by Django 5.1.3 on 2024-12-06 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0003_alter_shoppingcart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
