# Generated by Django 5.1.3 on 2024-12-06 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0004_alter_shoppingcart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
