# Generated by Django 5.1.3 on 2024-12-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipClub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("onemonth", "OneMonth"),
                            ("threemonths", "ThreeMonths"),
                            ("oneyear", "OneYear"),
                        ],
                        max_length=12,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "length",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("vip", "VIP"),
                        ],
                        max_length=7,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                ("discount_percentage", models.IntegerField(default=0)),
            ],
        ),
    ]
