# Generated by Django 5.1.3 on 2024-12-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_club", "0004_alter_membershipclub_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipclub",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
