# Generated by Django 5.1.3 on 2024-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_club", "0006_alter_membershipclub_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipclub",
            name="discount_percentage",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
