# Generated by Django 5.1.3 on 2024-12-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_club", "0007_alter_membershipclub_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipclub",
            name="length",
            field=models.CharField(
                choices=[
                    ("onemonth", "OneMonth"),
                    ("threemonths", "ThreeMonths"),
                    ("oneyear", "OneYear"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membershipclub",
            name="type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("vip", "VIP"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
