# Generated by Django 5.1.3 on 2024-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership_club", "0009_remove_membershipclub_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipclub",
            name="length",
            field=models.CharField(
                choices=[
                    ("unlimited", "Unlimited"),
                    ("onemonth", "OneMonth"),
                    ("threemonths", "ThreeMonths"),
                    ("oneyear", "OneYear"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
