# Generated by Django 5.1.3 on 2024-12-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipping_choice",
                    models.CharField(
                        choices=[
                            ("aircargo", "AirCargo"),
                            ("post", "Post"),
                            ("tipax", "Tipax"),
                        ],
                        default="tipax",
                        max_length=8,
                    ),
                ),
                ("fee", models.DecimalField(decimal_places=1, max_digits=10)),
                ("delivery_on", models.DateField()),
            ],
        ),
    ]
