# Generated by Django 5.1.3 on 2024-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_hues",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available_sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ManyToManyField(related_name="sizes", to="products.size"),
        ),
    ]
