# Generated by Django 5.1.3 on 2024-12-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
        migrations.CreateModel(
            name="ClotheSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[("s", "S"), ("m", "M"), ("l", "L")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoeSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            (35, "35"),
                            (36, "36"),
                            (37, "37"),
                            (38, "38"),
                            (39, "39"),
                            (40, "40"),
                            (41, "41"),
                            (42, "42"),
                            (43, "43"),
                            (44, "44"),
                            (45, "45"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClotheProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ManyToManyField(
                        related_name="clothe_sizes", to="products.clothesize"
                    ),
                ),
            ],
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="ShoeProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "size",
                    models.ManyToManyField(
                        related_name="shoe_sizes", to="products.shoesize"
                    ),
                ),
            ],
            bases=("products.product",),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
