# Generated by Django 5.1.3 on 2024-12-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_size_clothesize_shoesize_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hue", models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="clotheproduct",
            old_name="size",
            new_name="sizes",
        ),
        migrations.RenameField(
            model_name="shoeproduct",
            old_name="size",
            new_name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="hue",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.hue",
            ),
        ),
    ]
