# Generated by Django 5.1.3 on 2024-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_hue_rename_size_clotheproduct_sizes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("neutral", "Neutral"),
                ],
                max_length=7,
                null=True,
            ),
        ),
    ]
