# Generated by Django 5.1.3 on 2024-12-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="hue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.hue",
            ),
        ),
    ]
