# Generated by Django 5.1.3 on 2024-12-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clotheproduct",
            name="sizes",
            field=models.ManyToManyField(
                related_name="clothe_products", to="products.clothesize"
            ),
        ),
        migrations.AlterField(
            model_name="clothesize",
            name="size",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="shoeproduct",
            name="sizes",
            field=models.ManyToManyField(
                related_name="shoe_products", to="products.shoesize"
            ),
        ),
        migrations.AlterField(
            model_name="shoesize",
            name="size",
            field=models.IntegerField(
                choices=[
                    (35, "35"),
                    (36, "36"),
                    (37, "37"),
                    (38, "38"),
                    (39, "39"),
                    (40, "40"),
                    (41, "41"),
                    (42, "42"),
                    (43, "43"),
                    (44, "44"),
                    (45, "45"),
                ]
            ),
        ),
    ]
