# Generated by Django 5.1.3 on 2024-12-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=10, null=True
            ),
        ),
    ]
