# Generated by Django 5.1.3 on 2024-12-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoryProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="products.product",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        related_name="accessory_products", to="products.clothesize"
                    ),
                ),
            ],
            bases=("products.product",),
        ),
    ]
