# Generated by Django 5.1.3 on 2024-12-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_accessoryproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="for_couples",
            field=models.BooleanField(default=False),
        ),
    ]
