# Generated by Django 5.1.3 on 2024-12-06 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_product_for_couples"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="available_quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
